export const SUGGESTED_INFLUENCERS_FETCHING = "SUGGESTED_INFLUENCERS_FETCHING";
export const SUGGESTED_INFLUENCERS_FETCHED = "SUGGESTED_INFLUENCERS_FETCHED";
export const SUGGESTED_INFLUENCER_MOVE = "SUGGESTED_INFLUENCERS_MOVE";

export const STARRED_INFLUENCERS_FETCHING = "STARRED_INFLUENCERS_FETCHING";
export const STARRED_INFLUENCERS_FETCHED = "STARRED_INFLUENCERS_FETCHED";
export const STARRED_INFLUENCER_REMOVE = "STARRED_INFLUENCER_REMOVE";

export const SORT_BY_CHANGE = "SORT_BY_CHANGE";